name: expense_tracker
description: A Flutter expense tracker app
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  sqflite: ^2.3.0
  path: ^1.8.3
  sqflite_common_ffi: ^2.3.0
  google_fonts: ^6.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true